### ISSUE TITLE
[Question] How "CANSEE" work like ?

### ISSUE THREAD

**Issue by RageOfFire** [Tanguygab/PlayerList-PlaceholderAPI-Expansion#8]
as I expect "CANSEE" gonna to exclude player who vanish from game for example:
- Normal player see 7 players and then one player go vanish now they see 6 players
- Vanish player see 7 players and then they go vanish now they see 7 players
Here is my config:
```yml
playerlist:
    offline-text: Offline
    argument-separator: '||'
    lists:
      all:
        type: ONLINE
        included: true
        filters:
        - CANSEE
```
